- hosts: localhost
  gather_facts: false
  tasks:
    - name: Check that project_data_dir is set
      fail:
        msg: "project_data_dir is not set"
      when: project_data_dir is undefined or project_data_dir == ""

    - name: Fetch project repository
      when: project_data_repo|default(false)
      git:
        repo: "{{ project_data_repo }}"
        dest: "{{ project_data_dir }}"
        accept_hostkey: "{{ project_accept_hostkey|default(false)|bool }}"
        key_file: "{{ project_ssh_key|default(omit) }}"
      register: repo

    - name: Create projects
      when: repo is changed or project_force_create|default(false)|bool
      include_role:
        name: openshift_project
      vars:
        project_data: "{{ lookup('file', item)|from_yaml }}"
        project_name: "{{ item|basename|splitext|first }}"
      loop: "{{ query('fileglob', '%s/projects/*.yaml' % project_data_dir) }}"
